### ISSUE TITLE
Error transacting db.type/float

### ISSUE THREAD

**Issue by alex314159** [juji-io/datalevin#88] opened 2021-12-31 09:33 UTC
Hi,

I get the following error when transacting with a `db.type/float` schema. It works if `height` is not specified in the schema, is a `db.type/long` and also if it's a `db.type/double`.

```
(def schema {:name {:db/valueType :db.type/string}
             :height {:db/valueType :db.type/float}})
(d/transact! conn [{:name "John" :height 1.73}
                   {:name "Peter" :height 1.92}])
Execution error (ExceptionInfo) at datalevin.scan/get-first (scan.cljc:157).
Fail to get-first: "Error putting read-only transaction stop key buffer: \"Value out of range for int: 4286578688\""

```

Thank you,

**Comment by huahaiy** [comment] 2022-01-24 17:43
Acknowledged.

**Comment by huahaiy** [comment] 2022-02-25 05:26
I was not able to reproduce this error. I also added some generative tests for floats, and there was no error either. 

I would appreciate if you could provide a minimum case for this error. Probably it's something in the data.

**Comment by alex314159** [comment] 2022-02-25 11:05
Thanks for looking! This is literally all there was to it. Here's a minimal project with the error. https://github.com/alex314159/datomictests

This is Java 16 with --illegal-access=permit on Windows. The full launch pattern is

"C:\Program Files\Java\jdk-16.0.1\bin\java.exe" -Dfile.encoding=Cp1252 -XX:-OmitStackTraceInFastThrow -Dclojure.compile.path=C:\Users\AAlmosni\IdeaProjects\datomictests\target\classes -Ddatomictests.version=0.1.0-SNAPSHOT -Dclojure.debug=false --illegal-access=permit "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar=50660:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\bin" -classpath C:\Users\AAlmosni\IdeaProjects\datomictests\test;C:\Users\AAlmosni\IdeaProjects\datomictests\src;C:\Users\AAlmosni\IdeaProjects\datomictests\dev-resources;C:\Users\AAlmosni\IdeaProjects\datomictests\resources;C:\Users\AAlmosni\IdeaProjects\datomictests\target\classes;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jnr-ffi\2.2.2\jnr-ffi-2.2.2.jar;C:\Users\AAlmosni\.m2\repository\nrepl\nrepl\0.6.0\nrepl-0.6.0.jar;C:\Users\AAlmosni\.m2\repository\com\taoensso\encore\3.9.2\encore-3.9.2.jar;C:\Users\AAlmosni\.m2\repository\org\iq80\snappy\snappy\0.4\snappy-0.4.jar;C:\Users\AAlmosni\.m2\repository\clojure-complete\clojure-complete\0.2.5\clojure-complete-0.2.5.jar;C:\Users\AAlmosni\.m2\repository\org\msgpack\msgpack\0.6.12\msgpack-0.6.12.jar;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jffi\1.3.1\jffi-1.3.1.jar;C:\Users\AAlmosni\.m2\repository\org\ow2\asm\asm-analysis\9.1\asm-analysis-9.1.jar;C:\Users\AAlmosni\.m2\repository\com\taoensso\nippy\3.1.1\nippy-3.1.1.jar;C:\Users\AAlmosni\.m2\repository\javax\xml\bind\jaxb-api\2.3.0\jaxb-api-2.3.0.jar;C:\Users\AAlmosni\.m2\repository\org\babashka\sci\0.2.8\sci-0.2.8.jar;C:\Users\AAlmosni\.m2\repository\persistent-sorted-set\persistent-sorted-set\0.1.4\persistent-sorted-set-0.1.4.jar;C:\Users\AAlmosni\.m2\repository\org\lmdbjava\lmdbjava\0.8.2\lmdbjava-0.8.2.jar;C:\Users\AAlmosni\.m2\repository\org\clojure\clojure\1.10.3\clojure-1.10.3.jar;C:\Users\AAlmosni\.m2\repository\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jnr-a64asm\1.0.0\jnr-a64asm-1.0.0.jar;C:\Users\AAlmosni\.m2\repository\org\clojure\spec.alpha\0.2.194\spec.alpha-0.2.194.jar;C:\Users\AAlmosni\.m2\repository\borkdude\sci.impl.reflector\0.0.1\sci.impl.reflector-0.0.1.jar;C:\Users\AAlmosni\.m2\repository\datalevin\datalevin\0.5.28\datalevin-0.5.28.jar;C:\Users\AAlmosni\.m2\repository\org\ow2\asm\asm-util\9.1\asm-util-9.1.jar;C:\Users\AAlmosni\.m2\repository\borkdude\edamame\0.0.18\edamame-0.0.18.jar;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jnr-x86asm\1.0.2\jnr-x86asm-1.0.2.jar;C:\Users\AAlmosni\.m2\repository\org\clojure\core.specs.alpha\0.2.56\core.specs.alpha-0.2.56.jar;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jnr-constants\0.9.15\jnr-constants-0.9.15.jar;C:\Users\AAlmosni\.m2\repository\org\ow2\asm\asm-tree\9.1\asm-tree-9.1.jar;C:\Users\AAlmosni\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.13.1\jackson-core-2.13.1.jar;C:\Users\AAlmosni\.m2\repository\com\cognitect\transit-clj\1.0.324\transit-clj-1.0.324.jar;C:\Users\AAlmosni\.m2\repository\com\github\jnr\jffi\1.3.1\jffi-1.3.1-native.jar;C:\Users\AAlmosni\.m2\repository\com\taoensso\truss\1.6.0\truss-1.6.0.jar;C:\Users\AAlmosni\.m2\repository\org\clojure\tools.reader\1.3.4\tools.reader-1.3.4.jar;C:\Users\AAlmosni\.m2\repository\org\javassist\javassist\3.18.1-GA\javassist-3.18.1-GA.jar;C:\Users\AAlmosni\.m2\repository\org\lz4\lz4-java\1.7.1\lz4-java-1.7.1.jar;C:\Users\AAlmosni\.m2\repository\com\cognitect\transit-java\1.0.343\transit-java-1.0.343.jar;C:\Users\AAlmosni\.m2\repository\org\ow2\asm\asm-commons\9.1\asm-commons-9.1.jar;C:\Users\AAlmosni\.m2\repository\org\ow2\asm\asm\9.1\asm-9.1.jar;C:\Users\AAlmosni\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\AAlmosni\.m2\repository\org\tukaani\xz\1.8\xz-1.8.jar clojure.main -i C:\Users\AAlmosni\AppData\Local\Temp\1\form-init8705493524139860881.clj
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy (file:/C:/Users/AAlmosni/.m2/repository/org/lmdbjava/lmdbjava/0.8.2/lmdbjava-0.8.2.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by huahaiy** [comment] 2022-03-11 00:12
It seems to do with the packaged library. This could not be produced in internal tests, but can be produced when pulling in Datalevin as a library.

**Comment by rschmukler** [comment] 2022-04-20 00:16
Any update on this? I just ran into the same issue when using datalevin as a library in my project.

**Comment by huahaiy** [comment] 2022-04-20 06:56
This fix will be released soon.

**Closed** 2022-04-20 06:56 UTC

**Comment by rschmukler** [comment] 2022-04-20 14:57
Amazing, thank you for the quick response!
